return spectrum.Keybinding {
   -- numpad
   { key = "kp8", action = "move up", description = "Moves the character upward." },
   { key = "kp4", action = "move left", description = "Moves the character left." },
   { key = "kp2", action = "move down", description = "Moves the character downward." },
   { key = "kp6", action = "move right", description = "Moves the character right." },
   { key = "kp7", action = "move up-left", description = "Moves the character diagonally up-left." },
   { key = "kp9", action = "move up-right", description = "Moves the character diagonally up-right." },
   { key = "kp1", action = "move down-left", description = "Moves the character diagonally down-left." },
   { key = "kp3", action = "move down-right", description = "Moves the character diagonally down-right." },
   { key = "kp5", action = "wait", description = "Character waits and does nothing." },
   -- arrows
   { key = "up", action = "move up", description = "Moves the character upward." },
   { key = "left", action = "move left", description = "Moves the character left." },
   { key = "down", action = "move down", description = "Moves the character downward." },
   { key = "right", action = "move right", description = "Moves the character right." },
   { key = "left", mode = "shift", action = "move up-left", description = "Moves the character diagonally up-left." },
   {
      key = "right",
      mode = "shift",
      action = "move up-right",
      description = "Moves the character diagonally up-right.",
   },
   {
      key = "left",
      mode = "control",
      action = "move down-left",
      description = "Moves the character diagonally down-left.",
   },
   {
      key = "right",
      mode = "control",
      action = "move down-right",
      description = "Moves the character diagonally down-right.",
   },
   { key = ".", action = "wait", description = "Character waits and does nothing." },
   -- vi keys
   { key = "k", action = "move up", description = "Moves the character upward." },
   { key = "h", action = "move left", description = "Moves the character left." },
   { key = "j", action = "move down", description = "Moves the character downward." },
   { key = "l", action = "move right", description = "Moves the character right." },
   { key = "y", action = "move up-left", description = "Moves the character diagonally up-left." },
   { key = "u", action = "move up-right", description = "Moves the character diagonally up-right." },
   { key = "b", action = "move down-left", description = "Moves the character diagonally down-left." },
   { key = "n", action = "move down-right", description = "Moves the character diagonally down-right." },

   { key = "r", mode = "game-over", action = "restart", description = "Restarts the game." },
   { key = "q", mode = "game-over", action = "quit", description = "Quits the game." },
   { key = "space", action = "switch-kickmode", description = "Switches the kick mode." },
   { key = "f", action = "targeting", description = "Enters targeting mode." },
   { key = "tab", action = "inventory", description = "Opens the inventory screen." },
   { key = "backspace", action = "return", description = "Moves back up a level in a substate." },
   { key = "p", action = "pickup", description = "Picks up an inventory item." },
   -- { key = "space", action = "select", description = "Selects a target." },
   { key = "escape", mode = "title", action = "quit", description = "Quits the game." },
   { key = "escape", action = "pause", description = "Pauses and unpauses the game." },
   { key = "r", mode = "paused", action = "restart", description = "Restarts the game." },
   { key = "q", mode = "paused", action = "quit", description = "Quits the game." },
   { key = "w", mode = "paused", action = "move up", description = "Moves the selection upward." },
   { key = "a", mode = "paused", action = "move left", description = "Moves the selection left." },
   { key = "s", mode = "paused", action = "move down", description = "Moves the selection downward." },
   { key = "d", mode = "paused", action = "move right", description = "Moves the selection right." },
   { key = "escape", mode = "targeting", action = "return", description = "Exits targeting screen" },
   { key = "f", mode = "targeting", action = "select", description = "Selects a target." },
   { key = "space", mode = "targeting", action = "select", description = "Selects a target." },
   { key = "tab", mode = "targeting", action = "cycle", description = "Cycles through targets." },
}
