return spectrum.Keybinding {
   { key = "w", action = "move up", description = "Moves the character upward." },
   { key = "a", action = "move left", description = "Moves the character left." },
   { key = "s", action = "move down", description = "Moves the character downward." },
   { key = "d", action = "move right", description = "Moves the character right." },
   { key = "q", action = "move up-left", description = "Moves the character diagonally up-left." },
   { key = "e", action = "move up-right", description = "Moves the character diagonally up-right." },
   { key = "z", action = "move down-left", description = "Moves the character diagonally down-left." },
   { key = "c", action = "move down-right", description = "Moves the character diagonally down-right." },
   { key = "x", action = "wait", description = "Character waits and does nothing." },
   { key = "r", mode = "game-over", action = "restart", description = "Restarts the game." },
   { key = "q", mode = "game-over", action = "quit", description = "Quits the game." },
   { key = "f", action = "switch-kickmode", description = "Switches the kick mode." },
   { key = "tab", action = "inventory", description = "Opens the inventory screen." },
   { key = "backspace", action = "return", description = "Moves back up a level in a substate." },
   { key = "p", action = "pickup", description = "Picks up an inventory item." },
   { key = "space", action = "select", description = "Selects a target." },
   { key = "escape", mode = "title", action = "quit", description = "Quits the game." },
   { key = "escape", action = "pause", description = "Pauses and unpauses the game." },
   { key = "r", mode = "paused", action = "restart", description = "Restarts the game." },
   { key = "q", mode = "paused", action = "quit", description = "Quits the game." },
   { key = "w", mode = "paused", action = "move up", description = "Moves the character upward." },
   { key = "a", mode = "paused", action = "move left", description = "Moves the character left." },
   { key = "s", mode = "paused", action = "move down", description = "Moves the character downward." },
   { key = "d", mode = "paused", action = "move right", description = "Moves the character right." },
}
